server:
  port: 8081

spring:
  application:
    name: service-a

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    # How often client pulls registry copy (client-side cache)
    registry-fetch-interval-seconds: 30
    # How often it sends heartbeats (renewals)
    heartbeat-executor-thread-pool-size: 2

  instance:
    lease-renewal-interval-in-seconds: 30   # heartbeat interval (b)
    lease-expiration-duration-in-seconds: 90 # mark down after 90s (c)
